redir-port: 9797
mixed-port: 7890
tproxy-port: 0
allow-lan: true
geodata-mode: true
unified-delay: true
mode: rule
log-level: info
global-ua: clash-verge/v1.6.0
ipv6: false
tcp-concurrent: true
keep-alive-interval: 30
geo-auto-update: true
geo-update-interval: 24
geox-url:
  geoip: "https://jsd.onmicrosoft.cn/gh/Loyalsoldier/geoip@release/geoip.dat"
  geosite: "https://jsd.onmicrosoft.cn/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat"
  mmdb: "https://jsd.onmicrosoft.cn/gh/Loyalsoldier/geoip@release/Country.mmdb"
find-process-mode: strict
global-client-fingerprint: chrome

sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  skip-domain:
    - Mijia Cloud


profile:
  store-fake-ip: true
  store-selected: true

external-controller: 127.0.0.1:9090
external-ui: yacd
bind-address: "*"

tun:
  enable: true
  device: utun
  stack: mixed
  mtu: 1280
  dns-hijack:
    - any:53
  auto-route: true

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:1053
  enhanced-mode: redir-host
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*'
    - localhost.ptlogin2.qq.com
    - dns.msftncsi.com
    - www.msftncsi.com
    - www.msftconnecttest.com
    - time1.cloud.tencent.com
    - '+.lan'
    - '+.invalid.*'
    - '+.localhost'
    - '+.local.*'
    - '+.time.*'
    - '+.ntp.*'
    - '+.time.edu.cn'
    - '+.ntp.org.cn'
    - '+.pool.ntp.org'
    - '+.qpic.cn'
  nameserver-policy:
    'rule-set:CustomDirect':
      - "https://223.5.5.5/dns-query#ğŸ¼ CN"
      - "https://120.53.53.53/dns-query#ğŸ¼ CN"
    
    'rule-set:Microsoft':
      - "https://223.5.5.5/dns-query#ğŸ¼ CN"
      - "https://120.53.53.53/dns-query#ğŸ¼ CN"

    'rule-set:Onedrive':
      - "https://223.5.5.5/dns-query#ğŸ¼ CN"
      - "https://120.53.53.53/dns-query#ğŸ¼ CN"

    'rule-set:Copilot': 
      - "https://8.8.4.4/dns-query#ğŸ¤– Copilot"
      - "https://1.0.0.1/dns-query#ğŸ¤– Copilot"

    'rule-set:CustomProxy': 
      - "https://8.8.4.4/dns-query#â™»ï¸ Auto"
      - "https://1.0.0.1/dns-query#â™»ï¸ Auto"
    
    'rule-set:OpenAi': 
      - "https://8.8.4.4/dns-query#ğŸ¤– OpenAi"
      - "https://1.0.0.1/dns-query#ğŸ¤– OpenAi"

    'rule-set:Spotify': 
      - "https://8.8.4.4/dns-query#ğŸ¶ Spotify"
      - "https://1.0.0.1/dns-query#ğŸ¶ Spotify"
  
    'rule-set:Telegram': 
      - "https://8.8.4.4/dns-query#ğŸ“² Telegram"
      - "https://1.0.0.1/dns-query#ğŸ“² Telegram"

    'geosite:cn,private':
      - "https://223.5.5.5/dns-query#ğŸ¼ CN"
      - "https://120.53.53.53/dns-query#ğŸ¼ CN"
  
  nameserver:
    - "https://8.8.4.4/dns-query#â™»ï¸ Auto"
    - "https://1.0.0.1/dns-query#â™»ï¸ Auto"

  proxy-server-nameserver:
    - "https://223.5.5.5/dns-query#ğŸ¼ CN"
    - "https://120.53.53.53/dns-query#ğŸ¼ CN"


p: &p
    {type: http, interval: 86400, health-check: {enable: true, url: https://www.gstatic.com/generate_204, interval: 300}}
u: &u 
  type: url-test
  use:
    - ğŸ›« æœºåœº1
    - ğŸ›« æœºåœº2
    - ğŸ›« æœºåœº3
    - ğŸ›« æœºåœº4
    - ğŸ›« æœºåœº5
    - ğŸ›« æœºåœº6
  exclude-filter: "å¥—é¤|æµé‡|ç¾¤ç»„|é¢‘é“|å®˜ç½‘|æ¨èä½¿ç”¨|æµ‹è¯•|ç”µæŠ¥" #æ’é™¤æ»¡è¶³å…³é”®è¯æˆ–æ­£åˆ™è¡¨è¾¾å¼çš„èŠ‚ç‚¹
  exclude-type: "http" #æ’é™¤æŒ‡å®šç±»å‹çš„èŠ‚ç‚¹ï¼Œä¸æ”¯æŒæ­£åˆ™è¡¨è¾¾å¼ï¼Œé€šè¿‡ | åˆ†å‰²

proxy-providers:
# æœºåœºè®¢é˜…
# éœ€è¦ä¿®æ”¹æœºåœºåï¼Œè®¢é˜…ï¼Œå­˜å‚¨ç›®å½•
# åˆ«å¿˜äº†åŒæ—¶ä¿®æ”¹ èŠ‚ç‚¹ç­›é€‰éƒ¨åˆ†çš„æœºåœºå

  ğŸ›« æœºåœº1: {<<: *p, url: "https://igdux.top/~Clash", path: ./æœºåœº/æœºåœº1.yaml, override: {additional-prefix: "æœºåœº1 | "}}
  ğŸ›« æœºåœº2: {<<: *p, url: "è®¢é˜…åœ°å€2", path: ./æœºåœº/æœºåœº2.yaml, override: {additional-prefix: "æœºåœº2 | "}}
  ğŸ›« æœºåœº3: {<<: *p, url: "è®¢é˜…åœ°å€3", path: ./æœºåœº/æœºåœº3.yaml, override: {additional-prefix: "æœºåœº3 | "}}
  ğŸ›« æœºåœº4: {<<: *p, url: "è®¢é˜…åœ°å€4", path: ./æœºåœº/æœºåœº4.yaml, override: {additional-prefix: "æœºåœº4 | "}}
  ğŸ›« æœºåœº5: {<<: *p, url: "è®¢é˜…åœ°å€5", path: ./æœºåœº/æœºåœº5.yaml, override: {additional-prefix: "æœºåœº5 | "}}
  ğŸ›« æœºåœº6: {<<: *p, url: "è®¢é˜…åœ°å€6", path: ./æœºåœº/æœºåœº6.yaml, override: {additional-prefix: "æœºåœº6 | "}}

proxy-groups:
  #- {name: ğŸš€ Select, type: select, proxies: [â™»ï¸ Auto,ğŸ¼ CN], <<: *u}
  - {name: â™»ï¸ Auto, <<: *u, tolerance: 2, type: url-test}
  - {name: ğŸŒ Select1, type: select, <<: *u}
  - {name: ğŸŒ Select2, type: select, <<: *u}
  - {name: ğŸŒ Select3, type: select, <<: *u}
  - {name: ğŸ”¯ Load balancing, <<: *u, type: load-balance, strategy: consistent-hashing, url: 'https://www.gstatic.com/generate_204', interval: 300, lazy: true}
  - {name: ğŸ›  Fallback, <<: *u, type: fallback, url: 'https://www.gstatic.com/generate_204', interval: 300, lazy: true}
  - {name: ğŸ¤– OpenAi, type: select, proxies: [â™»ï¸ Auto,ğŸŒ Select1,ğŸŒ Select2,ğŸŒ Select3,ğŸ¼ CN]}
  - {name: ğŸ¤– Copilot, type: select, proxies: [â™»ï¸ Auto,ğŸŒ Select1,ğŸŒ Select2,ğŸŒ Select3,ğŸ¼ CN]}
  - {name: ğŸ¤– Gemini, type: select, proxies: [â™»ï¸ Auto,ğŸŒ Select1,ğŸŒ Select2,ğŸŒ Select3,ğŸ¼ CN]} 
  - {name: ğŸ¶ Spotify, type: select, proxies: [â™»ï¸ Auto,ğŸŒ Select1,ğŸŒ Select2,ğŸŒ Select3,ğŸ¼ CN]}
  - {name: â“‚ï¸ Microsoft, type: select, proxies: [ğŸ¼ CN,â™»ï¸ Auto,ğŸŒ Select1,ğŸŒ Select2,ğŸŒ Select3]}
  - {name: â˜ Onedrive, type: select, proxies: [ğŸ¼ CN,â™»ï¸ Auto,ğŸŒ Select1,ğŸŒ Select2,ğŸŒ Select3]}
  - {name: ğŸ” Google, type: select, proxies: [â™»ï¸ Auto,ğŸŒ Select1,ğŸŒ Select2,ğŸŒ Select3,ğŸ¼ CN]}
  - {name: ğŸ“² Telegram, type: select, proxies: [â™»ï¸ Auto]}
  - {name: ğŸ¼ CN, type: select, proxies: [DIRECT]}
  - {name: ğŸ‹ Final, type: select, proxies: [â™»ï¸ Auto]}

rule-providers:
  Microsoft:
    type: http
    behavior: classical
    format: yaml
    path: ./rule_providers/Microsoft.yaml
    url: "https://raw.githubusercontent.com/RiverFlowsInUUU/Rule/main/magisk/Microsoft.yaml"
    interval: 86400
  Onedrive:
    type: http
    behavior: classical
    format: yaml
    path: ./rule_providers/Onedrive.yaml
    url: "https://raw.githubusercontent.com/RiverFlowsInUUU/Rule/main/magisk/Onedrive.yaml"
    interval: 86400
  Copilot:
    type: http
    behavior: classical
    format: yaml
    path: ./rule_providers/Copilot.yaml
    url: "https://raw.githubusercontent.com/RiverFlowsInUUU/Rule/main/magisk/Copilot.yaml"
    interval: 86400
  Spotify:
    type: http
    behavior: classical
    format: yaml
    path: ./rule_providers/Spotify.yaml
    url: "https://raw.githubusercontent.com/RiverFlowsInUUU/Rule/main/magisk/Spotify.yaml"
    interval: 86400
  OpenAi:
    type: http
    behavior: classical
    format: yaml
    path: ./rule_providers/OpenAi.yaml
    url: "https://raw.githubusercontent.com/RiverFlowsInUUU/Rule/main/magisk/Openai.yaml"
    interval: 86400
  Google:
    type: http
    behavior: classical
    format: yaml
    path: ./rule_providers/Google.yaml
    url: "https://raw.githubusercontent.com/RiverFlowsInUUU/Rule/main/magisk/Google.yaml"
    interval: 86400
  Gemini:
    type: http
    behavior: classical
    format: yaml
    path: ./rule_providers/Gemini.yaml
    url: "https://raw.githubusercontent.com/RiverFlowsInUUU/Rule/main/magisk/Gemini.yaml"
    interval: 86400
  Telegram:
    type: http
    behavior: classical
    format: yaml
    path: ./rule_providers/Telegram.yaml
    url: "https://raw.githubusercontent.com/RiverFlowsInUUU/Rule/main/magisk/Telegram.yaml"
    interval: 86400
  CustomDirect:
    type: file
    behavior: classical
    path: ./rule_providers/userDirect.yaml
  
  CustomProxy:
    type: file
    behavior: classical
    path: ./rule_providers/userProxy.yaml
rules:
  - RULE-SET,Telegram,ğŸ“² Telegram
  - RULE-SET,Copilot,ğŸ¤– Copilot
  - RULE-SET,Gemini,ğŸ¤– Gemini
  - RULE-SET,OpenAi,ğŸ¤– OpenAi
  - RULE-SET,Spotify,ğŸ¶ Spotify
  - RULE-SET,Microsoft,â“‚ï¸ Microsoft
  - RULE-SET,Onedrive,â˜ Onedrive
  - RULE-SET,Google,ğŸ” Google
  - RULE-SET,CustomProxy,â™»ï¸ Auto
  - RULE-SET,CustomDirect,ğŸ¼ CN
  - GEOSITE,CN,ğŸ¼ CN
  - GEOIP,private,ğŸ¼ CN
  - GEOIP,CN,ğŸ¼ CN
  - MATCH,ğŸ‹ Final
