p: &p
    {type: http, interval: 86400, health-check: {enable: true, url: https://www.gstatic.com/generate_204, interval: 300}}
u: &u 
  type: url-test
  use:
    - ğŸ›« æœºåœº1
    - ğŸ›« æœºåœº2
    - ğŸ›« æœºåœº3
    - ğŸ›« æœºåœº4
    - ğŸ›« æœºåœº5
    - ğŸ›« æœºåœº6
  exclude-filter: "å¥—é¤|æµé‡|ç¾¤ç»„|é¢‘é“|å®˜ç½‘|æ¨èä½¿ç”¨|æµ‹è¯•|ç”µæŠ¥" #æ’é™¤æ»¡è¶³å…³é”®è¯æˆ–æ­£åˆ™è¡¨è¾¾å¼çš„èŠ‚ç‚¹
  exclude-type: "http" #æ’é™¤æŒ‡å®šç±»å‹çš„èŠ‚ç‚¹ï¼Œä¸æ”¯æŒæ­£åˆ™è¡¨è¾¾å¼ï¼Œé€šè¿‡ | åˆ†å‰²

proxy-providers:
# æœºåœºè®¢é˜…
# éœ€è¦ä¿®æ”¹æœºåœºåï¼Œè®¢é˜…ï¼Œå­˜å‚¨ç›®å½•
# åˆ«å¿˜äº†åŒæ—¶ä¿®æ”¹ èŠ‚ç‚¹ç­›é€‰éƒ¨åˆ†çš„æœºåœºå

  ğŸ›« æœºåœº1: {<<: *p, url: "https://igdux.top/~Clash", path: ./æœºåœº/æœºåœº1.yaml, override: {additional-prefix: "æœºåœº1 | "}}
  ğŸ›« æœºåœº2: {<<: *p, url: "", path: ./æœºåœº/æœºåœº2.yaml, override: {additional-prefix: "æœºåœº2 | "}}
  ğŸ›« æœºåœº3: {<<: *p, url: "", path: ./æœºåœº/æœºåœº3.yaml, override: {additional-prefix: "æœºåœº3 | "}}
  ğŸ›« æœºåœº4: {<<: *p, url: "", path: ./æœºåœº/æœºåœº4.yaml, override: {additional-prefix: "æœºåœº4 | "}}
  ğŸ›« æœºåœº5: {<<: *p, url: "", path: ./æœºåœº/æœºåœº5.yaml, override: {additional-prefix: "æœºåœº5 | "}}
  ğŸ›« æœºåœº6: {<<: *p, url: "", path: ./æœºåœº/æœºåœº6.yaml, override: {additional-prefix: "æœºåœº6 | "}}

proxy-groups:
  #- {name: ğŸš€ Select, type: select, proxies: [â™»ï¸ Auto,ğŸ¼ CN], <<: *u}
  - {name: â™»ï¸ Auto, <<: *u, tolerance: 2, type: url-test}
  - {name: ğŸŒ Select1, type: select, <<: *u}
  - {name: ğŸŒ Select2, type: select, <<: *u}
  - {name: ğŸŒ Select3, type: select, <<: *u}
  - {name: ğŸ”¯ Load balancing, <<: *u, type: load-balance, strategy: consistent-hashing, url: 'https://www.gstatic.com/generate_204', interval: 300, lazy: true}
  - {name: ğŸ›  Fallback, <<: *u, type: fallback, url: 'https://www.gstatic.com/generate_204', interval: 300, lazy: true}
  - {name: ğŸ¤– OpenAI, type: select, proxies: [â™»ï¸ Auto,ğŸŒ Select1,ğŸŒ Select2,ğŸŒ Select3,ğŸ¼ CN]}
  - {name: ğŸ¤– Copilot, type: select, proxies: [â™»ï¸ Auto,ğŸŒ Select1,ğŸŒ Select2,ğŸŒ Select3,ğŸ¼ CN]}
  - {name: ğŸ¶ Spotify, type: select, proxies: [â™»ï¸ Auto,ğŸŒ Select1,ğŸŒ Select2,ğŸŒ Select3,ğŸ¼ CN]}
  - {name: â“‚ï¸ Microsoft, type: select, proxies: [ğŸ¼ CN,â™»ï¸ Auto,ğŸŒ Select1,ğŸŒ Select2,ğŸŒ Select3]}
  - {name: â˜ Onedrive, type: select, proxies: [ğŸ¼ CN,â™»ï¸ Auto,ğŸŒ Select1,ğŸŒ Select2,ğŸŒ Select3]}
  - {name: ğŸ” Google, type: select, proxies: [â™»ï¸ Auto,ğŸŒ Select1,ğŸŒ Select2,ğŸŒ Select3,ğŸ¼ CN]}
  - {name: ğŸ¼ CN, type: select, proxies: [DIRECT]}
  - {name: ğŸ‹ Final, type: select, proxies: [â™»ï¸ Auto]}

rule-providers:
  Microsoft:
    type: http
    behavior: classical
    format: yaml
    path: ./rule/Microsoft.yaml
    url: "https://raw.githubusercontent.com/RiverFlowsInUUU/Rule/main/magisk/Microsoft.yaml"
    interval: 86400
  Onedrive:
    type: http
    behavior: classical
    format: yaml
    path: ./rule/Onedrive.yaml
    url: "https://raw.githubusercontent.com/RiverFlowsInUUU/Rule/main/magisk/Onedrive.yaml"
    interval: 86400
  Copilot:
    type: http
    behavior: classical
    format: yaml
    path: ./rule/Copilot.yaml
    url: "https://raw.githubusercontent.com/RiverFlowsInUUU/Rule/main/magisk/Copilot.yaml"
    interval: 86400
  Spotify:
    type: http
    behavior: classical
    format: yaml
    path: ./rule/Spotify.yaml
    url: "https://raw.githubusercontent.com/RiverFlowsInUUU/Rule/main/magisk/Spotify.yaml"
    interval: 86400
  Openai:
    type: http
    behavior: classical
    format: yaml
    path: ./rule/Openai.yaml
    url: "https://raw.githubusercontent.com/RiverFlowsInUUU/Rule/main/magisk/Openai.yaml"
    interval: 86400
  Google:
    type: http
    behavior: classical
    format: yaml
    path: ./rule/Google.yaml
    url: "https://raw.githubusercontent.com/RiverFlowsInUUU/Rule/main/magisk/Google.yaml"
    interval: 86400
  Gemini:
    type: http
    behavior: classical
    format: yaml
    path: ./rule/Gemini.yaml
    url: "https://raw.githubusercontent.com/RiverFlowsInUUU/Rule/main/magisk/Gemini.yaml"
    interval: 86400  
rules:
  - RULE-SET,Copilot,ğŸ¤– Copilot
  - RULE-SET,Openai,ğŸ¤– OpenAI
  - RULE-SET,Spotify,ğŸ¶ Spotify
  - RULE-SET,Microsoft,â“‚ï¸ Microsoft
  - RULE-SET,Onedrive,â˜ Onedrive
  - RULE-SET,Google,ğŸ” Google
  - GEOSITE,CN,ğŸ¼ CN
  - GEOIP,private,ğŸ¼ CN
  - GEOIP,CN,ğŸ¼ CN
  - MATCH,ğŸ‹ Final
