#å¦‚æœä¿®æ”¹äº†config.yamlå¹¶åˆ é™¤äº†userDirectï¼ŒuserProxyè§„åˆ™ç»„ï¼Œ
#æˆ–è€…ä¿®æ”¹äº†â€œä¸­å›½ç½‘å€â€å’Œâ€œä»£ç†â€ç­–ç•¥ç»„ï¼Œ
#è¯·æŠŠä¸‹é¢å¯¹åº”çš„nameserver-policyä¹Ÿåˆ é™¤ï¼Œå¦åˆ™å†…æ ¸å°†æ— æ³•å¯åŠ¨ã€‚
#Premiumå†…æ ¸å·²ç»åœæ›´ä¸å»ºè®®ä½¿ç”¨ï¼Œå¦‚æœæƒ³è¦åˆ‡æ¢è‡³Pæ ¸ï¼Œ
#è¯·è‡ªè¡Œæ ¹æ®pæ ¸æ–‡æ¡£ä¿®æ”¹ä¸‹é¢çš„é…ç½®ï¼Œå¦åˆ™å°†æ— æ³•å¯åŠ¨ã€‚
#----------------------------------------------
redir-port: 9797
mixed-port: 7890
tproxy-port: 9898
mode: rule
allow-lan: true
bind-address: '*'
unified-delay: false
tcp-concurrent: true
enable-process: true
find-process-mode: strict
log-level: info
ipv6: false
geodata-mode: true
#interface-name: tun0   #å‡ºå£ç½‘å¡åç§° å¯ç”¨æ¥æ¡¥æ¥VPNç±»è½¯ä»¶
#é¢æ¿å¯é€‰metacubexd/yacd æœ‰éœ€è¦è¯·è‡ªè¡Œä¿®æ”¹
external-controller: 0.0.0.0:9090
external-ui: dashboard/metacubexd
secret: ""
external-ui-url: "https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip"

geox-url:
  geoip: "https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geoip.dat"
  geosite: "https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat"
  mmdb: "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/Country.mmdb"
geo-auto-update: true
geo-update-interval: 48

profile:
  store-selected: true
  store-fake-ip: true

sniffer:
  enable: false
  parse-pure-ip: true
  override-destination: false
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  skip-domain:
    - "Mijia Cloud"

tun:
  enable: false
  device: utun
  stack: system
  dns-hijack:
    - any:53
  auto-route: false
  auto-detect-interface: false
  strict-route: false

dns:
  enable: true
  use-hosts: true
  perfer-h3: false
  ipv6-timeout: 300
  listen: 0.0.0.0:1053
  enhanced-mode: redir-host
  # redir-host / fake-ip å¯åˆ‡æ¢ï¼Œå»ºè®®ä½¿ç”¨redir-hosté¿å…dnsæ±¡æŸ“ï¼Œæ³„éœ²
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - "*"
    - "+.lan"
    - "+.local"
    - "localhost.ptlogin2.qq.com"

  nameserver-policy:
    'rule-set:CustomDirect':
      - "https://223.5.5.5/dns-query#ğŸ¼ CN"
      - "https://120.53.53.53/dns-query#ğŸ¼ CN"
    
    'rule-set:Microsoft':
      - "https://223.5.5.5/dns-query#ğŸ¼ CN"
      - "https://120.53.53.53/dns-query#ğŸ¼ CN"

    'rule-set:Onedrive':
      - "https://223.5.5.5/dns-query#ğŸ¼ CN"
      - "https://120.53.53.53/dns-query#ğŸ¼ CN"

    'rule-set:Copilot': 
      - "https://8.8.4.4/dns-query#ğŸ¤– Copilot"
      - "https://1.0.0.1/dns-query#ğŸ¤– Copilot"

    'rule-set:CustomProxy': 
      - "https://8.8.4.4/dns-query#â™»ï¸ Auto"
      - "https://1.0.0.1/dns-query#â™»ï¸ Auto"
    
    'rule-set:OpenAi': 
      - "https://8.8.4.4/dns-query#ğŸ¤– OpenAi"
      - "https://1.0.0.1/dns-query#ğŸ¤– OpenAi"

    'rule-set:Spotify': 
      - "https://8.8.4.4/dns-query#ğŸ¶ Spotify"
      - "https://1.0.0.1/dns-query#ğŸ¶ Spotify"

    'geosite:cn,private':
      - "https://223.5.5.5/dns-query#ğŸ¼ CN"
      - "https://120.53.53.53/dns-query#ğŸ¼ CN"
  
  nameserver:
    - "https://8.8.4.4/dns-query#â™»ï¸ Auto"
    - "https://1.0.0.1/dns-query#â™»ï¸ Auto"

  proxy-server-nameserver:
    - "https://223.5.5.5/dns-query#ğŸ¼ CN"
    - "https://120.53.53.53/dns-query#ğŸ¼ CN"


p: &p
    {type: http, interval: 86400, health-check: {enable: true, url: https://www.gstatic.com/generate_204, interval: 300}}
u: &u 
  type: url-test
  use:
    - ğŸ›« æœºåœº1
    - ğŸ›« æœºåœº2
    - ğŸ›« æœºåœº3
    - ğŸ›« æœºåœº4
    - ğŸ›« æœºåœº5
    - ğŸ›« æœºåœº6
  exclude-filter: "å¥—é¤|æµé‡|ç¾¤ç»„|é¢‘é“|å®˜ç½‘|æ¨èä½¿ç”¨|æµ‹è¯•|ç”µæŠ¥" #æ’é™¤æ»¡è¶³å…³é”®è¯æˆ–æ­£åˆ™è¡¨è¾¾å¼çš„èŠ‚ç‚¹
  exclude-type: "http" #æ’é™¤æŒ‡å®šç±»å‹çš„èŠ‚ç‚¹ï¼Œä¸æ”¯æŒæ­£åˆ™è¡¨è¾¾å¼ï¼Œé€šè¿‡ | åˆ†å‰²

proxy-providers:
# æœºåœºè®¢é˜…
# éœ€è¦ä¿®æ”¹æœºåœºåï¼Œè®¢é˜…ï¼Œå­˜å‚¨ç›®å½•
# åˆ«å¿˜äº†åŒæ—¶ä¿®æ”¹ èŠ‚ç‚¹ç­›é€‰éƒ¨åˆ†çš„æœºåœºå

  ğŸ›« æœºåœº1: {<<: *p, url: "https://igdux.top/~Clash", path: ./æœºåœº/æœºåœº1.yaml, override: {additional-prefix: "æœºåœº1 | "}}
  ğŸ›« æœºåœº2: {<<: *p, url: "", path: ./æœºåœº/æœºåœº2.yaml, override: {additional-prefix: "æœºåœº2 | "}}
  ğŸ›« æœºåœº3: {<<: *p, url: "", path: ./æœºåœº/æœºåœº3.yaml, override: {additional-prefix: "æœºåœº3 | "}}
  ğŸ›« æœºåœº4: {<<: *p, url: "", path: ./æœºåœº/æœºåœº4.yaml, override: {additional-prefix: "æœºåœº4 | "}}
  ğŸ›« æœºåœº5: {<<: *p, url: "", path: ./æœºåœº/æœºåœº5.yaml, override: {additional-prefix: "æœºåœº5 | "}}
  ğŸ›« æœºåœº6: {<<: *p, url: "", path: ./æœºåœº/æœºåœº6.yaml, override: {additional-prefix: "æœºåœº6 | "}}

proxy-groups:
  #- {name: ğŸš€ Select, type: select, proxies: [â™»ï¸ Auto,ğŸ¼ CN], <<: *u}
  - {name: â™»ï¸ Auto, <<: *u, tolerance: 2, type: url-test}
  - {name: ğŸŒ Select1, type: select, <<: *u}
  - {name: ğŸŒ Select2, type: select, <<: *u}
  - {name: ğŸŒ Select3, type: select, <<: *u}
  - {name: ğŸ”¯ Load balancing, <<: *u, type: load-balance, strategy: consistent-hashing, url: 'https://www.gstatic.com/generate_204', interval: 300, lazy: true}
  - {name: ğŸ›  Fallback, <<: *u, type: fallback, url: 'https://www.gstatic.com/generate_204', interval: 300, lazy: true}
  - {name: ğŸ¤– OpenAi, type: select, proxies: [â™»ï¸ Auto,ğŸŒ Select1,ğŸŒ Select2,ğŸŒ Select3,ğŸ¼ CN]}
  - {name: ğŸ¤– Copilot, type: select, proxies: [â™»ï¸ Auto,ğŸŒ Select1,ğŸŒ Select2,ğŸŒ Select3,ğŸ¼ CN]}
  - {name: ğŸ¤– Gemini, type: select, proxies: [â™»ï¸ Auto,ğŸŒ Select1,ğŸŒ Select2,ğŸŒ Select3,ğŸ¼ CN]} 
  - {name: ğŸ¶ Spotify, type: select, proxies: [â™»ï¸ Auto,ğŸŒ Select1,ğŸŒ Select2,ğŸŒ Select3,ğŸ¼ CN]}
  - {name: â“‚ï¸ Microsoft, type: select, proxies: [ğŸ¼ CN,â™»ï¸ Auto,ğŸŒ Select1,ğŸŒ Select2,ğŸŒ Select3]}
  - {name: â˜ Onedrive, type: select, proxies: [ğŸ¼ CN,â™»ï¸ Auto,ğŸŒ Select1,ğŸŒ Select2,ğŸŒ Select3]}
  - {name: ğŸ” Google, type: select, proxies: [â™»ï¸ Auto,ğŸŒ Select1,ğŸŒ Select2,ğŸŒ Select3,ğŸ¼ CN]}
  - {name: ğŸ¼ CN, type: select, proxies: [DIRECT]}
  - {name: ğŸ‹ Final, type: select, proxies: [â™»ï¸ Auto]}

rule-providers:
  Microsoft:
    type: http
    behavior: classical
    format: yaml
    path: ./rule_providers/Microsoft.yaml
    url: "https://raw.githubusercontent.com/RiverFlowsInUUU/Rule/main/magisk/Microsoft.yaml"
    interval: 86400
  Onedrive:
    type: http
    behavior: classical
    format: yaml
    path: ./rule_providers/Onedrive.yaml
    url: "https://raw.githubusercontent.com/RiverFlowsInUUU/Rule/main/magisk/Onedrive.yaml"
    interval: 86400
  Copilot:
    type: http
    behavior: classical
    format: yaml
    path: ./rule_providers/Copilot.yaml
    url: "https://raw.githubusercontent.com/RiverFlowsInUUU/Rule/main/magisk/Copilot.yaml"
    interval: 86400
  Spotify:
    type: http
    behavior: classical
    format: yaml
    path: ./rule_providers/Spotify.yaml
    url: "https://raw.githubusercontent.com/RiverFlowsInUUU/Rule/main/magisk/Spotify.yaml"
    interval: 86400
  OpenAi:
    type: http
    behavior: classical
    format: yaml
    path: ./rule_providers/OpenAi.yaml
    url: "https://raw.githubusercontent.com/RiverFlowsInUUU/Rule/main/magisk/Openai.yaml"
    interval: 86400
  Google:
    type: http
    behavior: classical
    format: yaml
    path: ./rule_providers/Google.yaml
    url: "https://raw.githubusercontent.com/RiverFlowsInUUU/Rule/main/magisk/Google.yaml"
    interval: 86400
  Gemini:
    type: http
    behavior: classical
    format: yaml
    path: ./rule_providers/Gemini.yaml
    url: "https://raw.githubusercontent.com/RiverFlowsInUUU/Rule/main/magisk/Gemini.yaml"
    interval: 86400
  CustomDirect:
    type: file
    behavior: classical
    path: ./rule_providers/userDirect.yaml
  
  CustomProxy:
    type: file
    behavior: classical
    path: ./rule_providers/userProxy.yaml
rules:
  - RULE-SET,Copilot,ğŸ¤– Copilot
  - RULE-SET,Gemini,ğŸ¤– Gemini
  - RULE-SET,OpenAi,ğŸ¤– OpenAi
  - RULE-SET,Spotify,ğŸ¶ Spotify
  - RULE-SET,Microsoft,â“‚ï¸ Microsoft
  - RULE-SET,Onedrive,â˜ Onedrive
  - RULE-SET,Google,ğŸ” Google
  - RULE-SET,CustomProxy,â™»ï¸ Auto
  - RULE-SET,CustomDirect,ğŸ¼ CN
  - GEOSITE,CN,ğŸ¼ CN
  - GEOIP,private,ğŸ¼ CN
  - GEOIP,CN,ğŸ¼ CN
  - MATCH,ğŸ‹ Final
