mixed-port: 7890
redir-port: 7891
tproxy-port: 1536
allow-lan: true
mode: Rule
geodata-mode: true
unified-delay: true
log-level: silent
ipv6: true
external-controller: 0.0.0.0:9090
#é¢æ¿é»˜è®¤Meta å¯é€‰Yacd æ¸…é™¤æµè§ˆå™¨ç¼“å­˜å³å¯é‡æ–°åŠ è½½
external-ui: ./dashboard/Meta #Yacd
secret: ""
tcp-concurrent: true
enable-process: true
find-process-mode: strict
global-client-fingerprint: chrome

#####################
#ä¿®æ”¹é…ç½®æ–‡ä»¶æ—¶ï¼Œå»ºè®®å…ˆåœæ­¢æ¨¡å—æœåŠ¡ï¼Œå†è¿›è¡Œä¿å­˜.
#####################

geox-url:
  geoip: "https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geoip.dat"
  geosite: "https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat"
  mmdb: "https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/country.mmdb"

profile:
  store-selected: true
  store-fake-ip: true

sniffer:
  enable: true
  sniff:
    TLS:
      ports: [443, 8443]
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true

tun:
  enable: false
  device: tun0
  stack: system
  dns-hijack:
    - 'any:53'
    - 'tcp://any:53'
  auto-route: true
  auto-detect-interface: true
  
dns:
  enable: true
  prefer-h3: true
  listen: 0.0.0.0:1053
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.1/8
  fake-ip-filter:
    - '*'
    - '+.lan'
    - 'connect.rom.miui.com'
    - 'localhost.ptlogin2.qq.com'
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
    
  p: &p
    {type: http, interval: 86400, health-check: {enable: true, url: https://www.gstatic.com/generate_204, interval: 300}}
  u: &u
    use:
    - ğŸ›« æœºåœº1
    - ğŸ›« æœºåœº2
    - ğŸ›« æœºåœº3
    - ğŸ›« æœºåœº4
    - ğŸ›« æœºåœº5
    - ğŸ›« æœºåœº6

proxy-providers:
  1.ğŸ›« æœºåœº1:
    <<: *p
    url: "è®¢é˜…åœ°å€1"
    path: ./proxy_providers/subscribe1.yaml
  
  2.ğŸ›« æœºåœº2:
    <<: *p
    url: "è®¢é˜…åœ°å€2"
    path: ./proxy_providers/subscribe2.yaml
  3.ğŸ›« æœºåœº1:
    <<: *p
    url: "è®¢é˜…åœ°å€3"
    path: ./proxy_providers/subscribe3.yaml
  4.ğŸ›« æœºåœº2:
    <<: *p
    url: "è®¢é˜…åœ°å€4"
    path: ./proxy_providers/subscribe4.yaml
  5.ğŸ›« æœºåœº1:
    <<: *p
    url: "è®¢é˜…åœ°å€5"
    path: ./proxy_providers/subscribe5.yaml
  6.ğŸ›« æœºåœº2:
    <<: *p
    url: "è®¢é˜…åœ°å€6"
    path: ./proxy_providers/subscribe6.yaml


proxy-groups:
  - {name: ğŸš€ Select, type: select, proxies: [â™»ï¸ Auto,ğŸ¼ CN], <<: *u}
  - {name: â™»ï¸ Auto, <<: *u, tolerance: 2, type: url-test}
  - {name: ğŸŒ Select1, type: select, proxies: [ğŸš€ Select,ğŸ¼ CN], <<: *u}
  - {name: ğŸŒ Select2, type: select, proxies: [ğŸš€ Select,ğŸ¼ CN], <<: *u}
  - {name: ğŸŒ Select3, type: select, proxies: [ğŸš€ Select,ğŸ¼ CN], <<: *u}
  - {name: ğŸ”¯ Load balancing, <<: *u, type: load-balance, strategy: consistent-hashing, url: 'https://www.gstatic.com/generate_204', interval: 300, lazy: true}
  - {name: ğŸ›  Fallback, <<: *u, type: fallback, url: 'https://www.gstatic.com/generate_204', interval: 300, lazy: true}
  - {name: ğŸ¤– OpenAI, type: select, proxies: [â™»ï¸ Auto,ğŸŒ Select1,ğŸŒ Select2,ğŸŒ Select3,ğŸ¼ CN]}
  - {name: ğŸ¤– Copilot, type: select, proxies: [â™»ï¸ Auto,ğŸŒ Select1,ğŸŒ Select2,ğŸŒ Select3,ğŸ¼ CN]}
  - {name: ğŸ¶ Spotify, type: select, proxies: [â™»ï¸ Auto,ğŸŒ Select1,ğŸŒ Select2,ğŸŒ Select3,ğŸ¼ CN]}
  - {name: â“‚ï¸ Microsoft, type: select, proxies: [ğŸ¼ CN,â™»ï¸ Auto,ğŸŒ Select1,ğŸŒ Select2,ğŸŒ Select3]}
  - {name: â˜ Onedrive, type: select, proxies: [ğŸ¼ CN,â™»ï¸ Auto,ğŸŒ Select1,ğŸŒ Select2,ğŸŒ Select3]}
  - {name: ğŸ” Google, type: select, proxies: [â™»ï¸ Auto,ğŸŒ Select1,ğŸŒ Select2,ğŸŒ Select3,ğŸ¼ CN]}
  - {name: ğŸ¼ CN, type: select, proxies: [DIRECT]}
  - {name: ğŸ‹ Final, type: select, proxies: [ğŸ¼ CN]}

rule-providers:
  Microsoft:
    type: http
    behavior: classical
    format: yaml
    path: ./rule/Microsoft.yaml
    url: "https://raw.githubusercontent.com/RiverFlowsInUUU/Rule/main/magisk/Microsoft.yaml"
    interval: 86400
  Onedrive:
    type: http
    behavior: classical
    format: yaml
    path: ./rule/Onedrive.yaml
    url: "https://raw.githubusercontent.com/RiverFlowsInUUU/Rule/main/magisk/Onedrive.yaml"
    interval: 86400
  Copilot:
    type: http
    behavior: classical
    format: yaml
    path: ./rule/Copilot.yaml
    url: "https://raw.githubusercontent.com/RiverFlowsInUUU/Rule/main/magisk/Copilot.yaml"
    interval: 86400
  Spotify:
    type: http
    behavior: classical
    format: yaml
    path: ./rule/Spotify.yaml
    url: "https://raw.githubusercontent.com/RiverFlowsInUUU/Rule/main/magisk/Spotify.yaml"
    interval: 86400
  Openai:
    type: http
    behavior: classical
    format: yaml
    path: ./rule/Openai.yaml
    url: "https://raw.githubusercontent.com/RiverFlowsInUUU/Rule/main/magisk/Openai.yaml"
    interval: 86400
  Google:
    type: http
    behavior: classical
    format: yaml
    path: ./rule/Google.yaml
    url: "https://raw.githubusercontent.com/RiverFlowsInUUU/Rule/main/magisk/Google.yaml"
    interval: 86400
  Gemini:
    type: http
    behavior: classical
    format: yaml
    path: ./rule/Gemini.yaml
    url: "https://raw.githubusercontent.com/RiverFlowsInUUU/Rule/main/magisk/Gemini.yaml"
    interval: 86400  
rules:
  - RULE-SET,Bing,ğŸ¤– Copilot
  - RULE-SET,Openai,ğŸ¤– OpenAI
  - RULE-SET,Spotify,ğŸ¶ Spotify
  - RULE-SET,Microsoft,â“‚ï¸ Microsoft
  - RULE-SET,Onedrive,â˜ Onedrive
  - RULE-SET,Google,ğŸ” Google
  - GEOSITE,CN,ğŸ¼ CN
  - GEOIP,private,ğŸ¼ CN,no-resolve
  - GEOIP,CN,ğŸ¼ CN,no-resolve
  - MATCH,ğŸ‹ Final
