mixed-port: 7890
redir-port: 9797
tproxy-port: 9898
mode: rule # è¿è¡Œæ¨¡å¼ï¼šrule è§„åˆ™åŒ¹é…ï¼›global å…¨å±€ä»£ç†(éœ€è¦åœ¨GLOBALç­–ç•¥ç»„é€‰æ‹©ä»£ç†/ç­–ç•¥)ï¼›direct å…¨å±€ç›´è¿
find-process-mode: strict # è¿›ç¨‹åŒ¹é…æ¨¡å¼ï¼šalways å¼€å¯ï¼Œå¼ºåˆ¶åŒ¹é…æ‰€æœ‰è¿›ç¨‹ï¼›ï¼›strict é»˜è®¤ï¼Œç”± Clash åˆ¤æ–­æ˜¯å¦å¼€å¯ï¼›off ä¸åŒ¹é…è¿›ç¨‹ï¼Œæ¨èåœ¨è·¯ç”±å™¨ä¸Šä½¿ç”¨æ­¤æ¨¡å¼
global-client-fingerprint: random # å…¨å±€å®¢æˆ·ç«¯æŒ‡çº¹ï¼Œå¯é€‰ï¼š"chrome", "firefox", "safari", "iOS", "android", "edge", "360"," qq", "random"ï¼›è‹¥é€‰æ‹© "random", åˆ™æŒ‰ Cloudflare Radar æ•°æ®æŒ‰æ¦‚ç‡ç”Ÿæˆä¸€ä¸ªç°ä»£æµè§ˆå™¨æŒ‡çº¹ã€‚
global-ua: clash.meta # è‡ªå®šä¹‰å¤–éƒ¨èµ„æºä¸‹è½½æ—¶ä½¿ç”¨çš„UA,é»˜è®¤ä¸º clash.meta
log-level: error # æ—¥å¿—çº§åˆ«ï¼šsilent é™é»˜ï¼Œä¸è¾“å‡ºï¼›error ä»…è¾“å‡ºå‘ç”Ÿé”™è¯¯è‡³æ— æ³•ä½¿ç”¨çš„æ—¥å¿—ï¼›warning è¾“å‡ºå‘ç”Ÿé”™è¯¯ä½†ä¸å½±å“è¿è¡Œçš„æ—¥å¿—ï¼Œä»¥åŠ error çº§åˆ«å†…å®¹ï¼›info è¾“å‡ºä¸€èˆ¬è¿è¡Œçš„å†…å®¹ï¼Œä»¥åŠ error å’Œ warning çº§åˆ«çš„æ—¥å¿—ï¼›debug å°½å¯èƒ½çš„è¾“å‡ºè¿è¡Œä¸­æ‰€æœ‰çš„ä¿¡æ¯
allow-lan: true # å…è®¸å±€åŸŸç½‘å†…å…¶ä»–è®¾å¤‡ç»è¿‡ Clash çš„ä»£ç†ç«¯å£è®¿é—®äº’è”ç½‘ï¼Œå¯é€‰å€¼ true/false
bind-address: "*" # ç»‘å®š IP, é€šè¿‡ LAN è®¿é—®ä¸€ä¸ª/ä¸€äº›ç‰¹å®šçš„ IP åœ°å€ï¼Œ"*" ç»‘å®šæ‰€æœ‰ IP åœ°å€ï¼Œé»˜è®¤å€¼ï¼Œä¸å¡«å†™æ­¤é¡¹åˆ™ç»‘å®šå…¨éƒ¨
ipv6: false # æ˜¯å¦å…è®¸å†…æ ¸æ¥å— IPv6 æµé‡ï¼Œå¯é€‰å€¼ true/false
tcp-concurrent: true # tcpå¹¶å‘ï¼Œå…è®¸åŒæ—¶å¤„ç†å¤šä¸ªtcpè¿æ¥ï¼Œå¯é€‰å€¼ true/false
keep-alive-interval: 30 # TCP Keep Alive é—´éš”,å•ä½åˆ†é’Ÿ | æ§åˆ¶ Clash å‘å‡º TCP Keep Alive åŒ…çš„é—´éš”,å‡å°‘ç§»åŠ¨è®¾å¤‡è€—ç”µé—®é¢˜çš„ä¸´æ—¶æªæ–½
unified-delay: true # ç»Ÿä¸€å»¶è¿Ÿï¼Œæ›´æ¢å»¶è¿Ÿè®¡ç®—æ–¹å¼,å»é™¤æ¡æ‰‹ç­‰é¢å¤–å»¶è¿Ÿ å¯é€‰å€¼ true/false
external-controller: 0.0.0.0:9090
external-ui: dashboard/metacubexd
secret: ""
external-ui-url: "https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip"

# GEOæ–‡ä»¶é…ç½®
geodata-mode: true # GeoIP ä½¿ç”¨çš„æ–‡ä»¶,å¯é€‰ true ä¸º.dat/ false ä¸º.mmdb
geosite-matcher: succinct # GeoSite ä½¿ç”¨çš„åŒ¹é…å™¨å®ç°ï¼Œå¯é€‰ï¼šsuccinctï¼šä¸è§„åˆ™é›†ç›¸åŒï¼›mphï¼šæ¥è‡ª V2Rayï¼Œä¹Ÿæ˜¯ Xray ä¸­çš„â€œæ··åˆâ€
geodata-loader: memconservative # GEO æ–‡ä»¶åŠ è½½æ¨¡å¼ï¼šstandardï¼šæ ‡å‡†åŠ è½½å™¨ï¼›memconservativeï¼šä¸“ä¸ºå†…å­˜å—é™(å°å†…å­˜)è®¾å¤‡ä¼˜åŒ–çš„åŠ è½½å™¨(é»˜è®¤å€¼)
geo-auto-update: true # è‡ªåŠ¨æ›´æ–° GEO æ–‡ä»¶,å¯é€‰ true/false
geo-update-interval: 72 # æ›´æ–°é—´éš”,å•ä½ï¼šå°æ—¶
geox-url: # è‡ªå®šä¹‰ GEO æ–‡ä»¶ä¸‹è½½åœ°å€
  geoip: "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip.dat"
  geosite: "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat"
  mmdb: "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/country.mmdb"
  asn: "https://github.com/xishang0128/geoip/releases/download/latest/GeoLite2-ASN.mmdb"

# å¤–éƒ¨æ§åˆ¶ (API)
external-controller: 127.0.0.1:9090 # å¤–éƒ¨æ§åˆ¶å™¨ï¼Œå¯ä»¥ä½¿ç”¨ RESTful API æ¥æ§åˆ¶ä½ çš„ Clash å†…æ ¸ï¼›API ç›‘å¬åœ°å€ï¼Œä½ å¯ä»¥å°† 127.0.0.1 ä¿®æ”¹ä¸º 0.0.0.0 æ¥ç›‘å¬æ‰€æœ‰ IPï¼›è®¿é—®åœ°å€ï¼šhttp://127.0.0.1:9090
secret: "ksc666" # API çš„è®¿é—®å¯†é’¥
external-ui: "./ui" # å¤–éƒ¨ç”¨æˆ·ç•Œé¢è·¯å¾„ï¼Œå¯ä»¥ä¸ºç»å¯¹è·¯å¾„ï¼Œæˆ–è€… Clash å·¥ä½œç›®å½•çš„ç›¸å¯¹è·¯å¾„
external-ui-name: "metacubexd" # è‡ªå®šä¹‰å¤–éƒ¨ç”¨æˆ·ç•Œé¢åå­—
external-ui-url: "https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip" # è‡ªå®šä¹‰å¤–éƒ¨ç”¨æˆ·ç•Œé¢ä¸‹è½½åœ°å€

profile: # ç¼“å­˜
  store-selected: true # å‚¨å­˜ API å¯¹ç­–ç•¥ç»„çš„é€‰æ‹©ï¼Œä»¥ä¾›ä¸‹æ¬¡å¯åŠ¨æ—¶ä½¿ç”¨
  store-fake-ip: true # å‚¨å­˜ fakeip æ˜ å°„è¡¨ï¼ŒåŸŸåå†æ¬¡å‘ç”Ÿè¿æ¥æ—¶ï¼Œä½¿ç”¨åŸæœ‰æ˜ å°„åœ°å€

sniffer: # åŸŸåå—…å™¨,é€šè¿‡è¯»å–æ¡æ‰‹åŒ…å†…çš„åŸŸåå­—æ®µ,å°†IPè¿˜åŸæˆåŸŸå,æœ‰æ•ˆè§£å†³Mappingæœºåˆ¶çš„çŸ­æ¿
  enable: true
  force-dns-mapping: true # å¯¹ redir-host ç±»å‹è¯†åˆ«çš„æµé‡è¿›è¡Œå¼ºåˆ¶å—…æ¢
  parse-pure-ip: true # å¯¹æ‰€æœ‰æœªè·å–åˆ°åŸŸåçš„æµé‡è¿›è¡Œå¼ºåˆ¶å—…æ¢
  override-destination: true # æ˜¯å¦ä½¿ç”¨å—…æ¢ç»“æœä½œä¸ºå®é™…è®¿é—®,é»˜è®¤ä¸º true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true # å¯è¦†ç›– sniffer.override-destination
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  force-domain: # éœ€è¦å¼ºåˆ¶å—…æ¢çš„åŸŸåï¼ˆé»˜è®¤æƒ…å†µä¸‹åªå¯¹IPè¿›è¡Œå—…æ¢ï¼‰
    - "+.v2ex.com"
  skip-domain: # éœ€è¦è·³è¿‡å—…æ¢çš„åŸŸåã€‚ä¸»è¦è§£å†³éƒ¨åˆ†ç«™ç‚¹sniå­—æ®µéåŸŸåï¼Œå¯¼è‡´å—…æ¢ç»“æœå¼‚å¸¸çš„é—®é¢˜ï¼Œå¦‚ç±³å®¶è®¾å¤‡
    - "Mijia Cloud"

tun:
  enable: false # æ˜¯å¦å¯ç”¨,å¯é€‰ true/false
  stack: mixed # tun æ¨¡å¼å †æ ˆï¼Œå¦‚æ— ä½¿ç”¨é—®é¢˜ï¼Œå»ºè®®ä½¿ç”¨ mixedæ ˆï¼Œé»˜è®¤ gvisorï¼Œå¯ç”¨å€¼ï¼š system/gvisor/mixed
  auto-route: true # è‡ªåŠ¨è®¾ç½®å…¨å±€è·¯ç”±,å¯ä»¥è‡ªåŠ¨å°†å…¨å±€æµé‡è·¯ç”±è¿›å…¥ tun ç½‘å¡
  auto-detect-interface: true # è‡ªåŠ¨é€‰æ‹©æµé‡å‡ºå£æ¥å£,å¤šå‡ºå£ç½‘å¡åŒæ—¶è¿æ¥çš„è®¾å¤‡å»ºè®®æ‰‹åŠ¨æŒ‡å®šå‡ºå£ç½‘å¡
  dns-hijack: # dns åŠ«æŒï¼Œå°†åŒ¹é…åˆ°çš„è¿æ¥å¯¼å…¥å†…éƒ¨ dns æ¨¡å—ï¼Œä¸ä¹¦å†™åè®®åˆ™ä¸º udp://
    - "any:53"
  device: Meta # æŒ‡å®š tun ç½‘å¡åç§°,MacOS è®¾å¤‡åªèƒ½ä½¿ç”¨ utun å¼€å¤´çš„ç½‘å¡å
  mtu: 9000 # æœ€å¤§ä¼ è¾“å•å…ƒï¼Œä¼šå½±å“æé™çŠ¶æ€ä¸‹çš„é€Ÿç‡ï¼Œä¸€èˆ¬ç”¨æˆ·é»˜è®¤å³å¯ã€‚
  strict-route: false # ä¸¥æ ¼è·¯ç”±ï¼Œæ‰€æœ‰è¿æ¥è·¯ç”±åˆ° tun æ¥é˜²æ­¢æ³„æ¼,ä½†è®¾å¤‡å°†æ— æ³•è¢«å…¶ä»–è®¾å¤‡è®¿é—®
  gso: true # å¯ç”¨é€šç”¨åˆ†æ®µå¸è½½,ä»…æ”¯æŒ Linux
  gso-max-size: 65536 # æ•°æ®å—çš„æœ€å¤§é•¿åº¦
  udp-timeout: 300 # UDP NAT è¿‡æœŸæ—¶é—´,ä»¥ç§’ä¸ºå•ä½,é»˜è®¤ä¸º 300(5 åˆ†é’Ÿ)
  endpoint-independent-nat: false # å¯ç”¨ç‹¬ç«‹äºç«¯ç‚¹çš„ NAT,æ€§èƒ½å¯èƒ½ä¼šç•¥æœ‰ä¸‹é™,æ‰€ä»¥ä¸å»ºè®®åœ¨ä¸éœ€è¦çš„æ—¶å€™å¼€å¯
  inet4-route-exclude-address: #å¯ç”¨ auto-route æ—¶æ’é™¤è‡ªå®šä¹‰ç½‘æ®µ
    - 192.168.0.0/16
  inet6-route-exclude-address: #å¯ç”¨ auto-route æ—¶æ’é™¤è‡ªå®šä¹‰ç½‘æ®µ
    - fc00::/7

dns:
  enable: true
  prefer-h3: true # ä¼˜å…ˆä½¿ç”¨ DOH çš„ http/3
  listen: 0.0.0.0:1053
  ipv6: true
  ipv6-timeout: 300 # ipv6è¶…æ—¶ï¼Œå•ä½ æ¯«ç§’
  cache-algorithm: arc # ç¼“å­˜ç®—æ³•
  use-hosts: true # æŸ¥è¯¢ç³»ç»ŸHosts
  default-nameserver: # é»˜è®¤ DNS, ç”¨äºè§£æ DNS æœåŠ¡å™¨ çš„åŸŸåï¼Œå¿…é¡»ä¸º IP, å¯ä¸ºåŠ å¯† DNS
    - 'https://1.12.12.12/dns-query'
    - 'https://[2400:3200::1]/dns-query'
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.0/16
  fake-ip-filter: # fakeip è¿‡æ»¤ï¼Œä»¥ä¸‹åœ°å€ä¸ä¼šä¸‹å‘ fakeip æ˜ å°„ç”¨äºè¿æ¥
    - '*'
    - '+.lan'
    - '+.local'
  nameserver-policy: # æŒ‡å®šåŸŸåæŸ¥è¯¢çš„è§£ææœåŠ¡å™¨ï¼Œä¼˜å…ˆäº nameserver/fallback æŸ¥è¯¢
    "geosite:cn,private":
      - 'https://1.12.12.12/dns-query'
      - 'https://223.5.5.5/dns-query'
      - 'https://[2400:3200::1]/dns-query'
      - 'https://[2402:4e00::]/dns-query'
  nameserver: # é»˜è®¤çš„åŸŸåè§£ææœåŠ¡å™¨ï¼Œå¦‚ä¸é…ç½® fallback/proxy-server-nameserver , åˆ™æ‰€æœ‰åŸŸåéƒ½ç”± nameserver è§£æ
    - 'https://1.1.1.1/dns-query#ğŸŒDNSè§£æ'
    - 'https://8.8.8.8/dns-query#ğŸŒDNSè§£æ'
    - 'https://[2606:4700:4700::1111]/dns-query#ğŸŒDNSè§£æ'
    - 'https://[2001:4860:4860::8888]/dns-query#ğŸŒDNSè§£æ'
  proxy-server-nameserver: # ä»£ç†èŠ‚ç‚¹åŸŸåè§£ææœåŠ¡å™¨ï¼Œä»…ç”¨äºè§£æä»£ç†èŠ‚ç‚¹çš„åŸŸå
    - 'https://1.1.1.1/dns-query#ğŸŒDNSè§£æ'
    - 'https://8.8.8.8/dns-query#ğŸŒDNSè§£æ'

  p: &p
    {type: http, interval: 86400, health-check: {enable: true, url: https://www.gstatic.com/generate_204, interval: 300}}
  u: &u
    use:
    - 1.ä¸»è¦åœ°å€
    - 2.å¤‡ç”¨åœ°å€

proxy-providers:
  1.ä¸»è¦åœ°å€:
    <<: *p
    url: "è®¢é˜…åœ°å€1"
    path: ./proxy_providers/subscribe1.yaml
    #æ³¨æ„ï¼å¦‚æœæ‚¨çš„è®¢é˜…é“¾æ¥ä¸­å¸¦æœ‰â€œ&â€å­—ç¬¦ï¼Œè¯·åˆ æ‰.
  2.å¤‡ç”¨åœ°å€:
    <<: *p
    url: "è®¢é˜…åœ°å€2"
    path: ./proxy_providers/subscribe2.yaml
    #æ³¨æ„ï¼å¦‚æœæ‚¨çš„è®¢é˜…é“¾æ¥ä¸­å¸¦æœ‰â€œ&â€å­—ç¬¦ï¼Œè¯·åˆ æ‰.
proxy-groups:
  - {name: ğŸ¯ æ€»æ¨¡å¼, type: select, proxies: [ğŸš€ èŠ‚ç‚¹é€‰æ‹©,â™»ï¸ è‡ªåŠ¨åˆ‡æ¢,â™»ï¸ æ‰‹åŠ¨åˆ‡æ¢1,â™»ï¸ æ‰‹åŠ¨åˆ‡æ¢2,â™»ï¸ æ‰‹åŠ¨åˆ‡æ¢3,ğŸŒ ç›´è¿]}
  - {name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©, type: select, proxies: [â™»ï¸ è‡ªåŠ¨åˆ‡æ¢,ğŸŒ ç›´è¿], <<: *u}
  - {name: â™»ï¸ è‡ªåŠ¨åˆ‡æ¢, <<: *u, tolerance: 2, type: url-test}
  - {name: â™»ï¸ æ‰‹åŠ¨åˆ‡æ¢1, type: select, proxies: [ğŸš€ èŠ‚ç‚¹é€‰æ‹©,ğŸŒ ç›´è¿], <<: *u}
  - {name: â™»ï¸ æ‰‹åŠ¨åˆ‡æ¢2, type: select, proxies: [ğŸš€ èŠ‚ç‚¹é€‰æ‹©,ğŸŒ ç›´è¿], <<: *u}
  - {name: â™»ï¸ æ‰‹åŠ¨åˆ‡æ¢3, type: select, proxies: [ğŸš€ èŠ‚ç‚¹é€‰æ‹©,ğŸŒ ç›´è¿], <<: *u}
  - {name: ğŸ¤– OpenAI, type: select, proxies: [ğŸ¯ æ€»æ¨¡å¼,â™»ï¸ è‡ªåŠ¨åˆ‡æ¢,â™»ï¸ æ‰‹åŠ¨åˆ‡æ¢1,â™»ï¸ æ‰‹åŠ¨åˆ‡æ¢2,â™»ï¸ æ‰‹åŠ¨åˆ‡æ¢3,ğŸŒ ç›´è¿]}
  - {name: â“‚ï¸ å¾®è½¯Bing, type: select, proxies: [ğŸ¯ æ€»æ¨¡å¼,â™»ï¸ è‡ªåŠ¨åˆ‡æ¢,â™»ï¸ æ‰‹åŠ¨åˆ‡æ¢1,â™»ï¸ æ‰‹åŠ¨åˆ‡æ¢2,â™»ï¸ æ‰‹åŠ¨åˆ‡æ¢3,ğŸŒ ç›´è¿]}
  - {name: ğŸ¶ Spotify, type: select, proxies: [ğŸ¯ æ€»æ¨¡å¼,â™»ï¸ è‡ªåŠ¨åˆ‡æ¢,â™»ï¸ æ‰‹åŠ¨åˆ‡æ¢1,â™»ï¸ æ‰‹åŠ¨åˆ‡æ¢2,â™»ï¸ æ‰‹åŠ¨åˆ‡æ¢3,ğŸŒ ç›´è¿]}
  - {name: â“‚ï¸ å¾®è½¯æœåŠ¡, type: select, proxies: [ğŸŒ ç›´è¿,ğŸ¯ æ€»æ¨¡å¼,â™»ï¸ è‡ªåŠ¨åˆ‡æ¢,â™»ï¸ æ‰‹åŠ¨åˆ‡æ¢1,â™»ï¸ æ‰‹åŠ¨åˆ‡æ¢2,â™»ï¸ æ‰‹åŠ¨åˆ‡æ¢3]}
  - {name: â“‚ï¸ å¾®è½¯äº‘ç›˜, type: select, proxies: [ğŸŒ ç›´è¿,ğŸ¯ æ€»æ¨¡å¼,â™»ï¸ è‡ªåŠ¨åˆ‡æ¢,â™»ï¸ æ‰‹åŠ¨åˆ‡æ¢1,â™»ï¸ æ‰‹åŠ¨åˆ‡æ¢2,â™»ï¸ æ‰‹åŠ¨åˆ‡æ¢3]}
  - {name: ğŸ“¢ è°·æ­ŒæœåŠ¡, type: select, proxies: [ğŸ¯ æ€»æ¨¡å¼,â™»ï¸ è‡ªåŠ¨åˆ‡æ¢,â™»ï¸ æ‰‹åŠ¨åˆ‡æ¢1,â™»ï¸ æ‰‹åŠ¨åˆ‡æ¢2,â™»ï¸ æ‰‹åŠ¨åˆ‡æ¢3,ğŸŒ ç›´è¿]}
  - {name: ğŸ›‘ å¹¿å‘Šæ‹¦æˆª, type: select, proxies: [REJECT,ğŸŒ ç›´è¿]}
  - {name: ğŸ‹ æ¼ç½‘ä¹‹é±¼, type: select, proxies: [ğŸ¯ æ€»æ¨¡å¼,ğŸŒ ç›´è¿]}
  - {name: ğŸŒ ç›´è¿, type: select, proxies: [DIRECT]}
rule-providers:
  Microsoft:
    type: http
    behavior: classical
    format: yaml
    path: ./rule_providers/Microsoft.yaml
    url: "https://raw.githubusercontent.com/RiverFlowsInUUU/Rule/main/magisk/Microsoft.yaml"
    interval: 86400
  Onedrive:
    type: http
    behavior: classical
    format: yaml
    path: ./rule_providers/Onedrive.yaml
    url: "https://raw.githubusercontent.com/RiverFlowsInUUU/Rule/main/magisk/Onedrive.yaml"
    interval: 86400
  Bing:
    type: http
    behavior: classical
    format: yaml
    path: ./rule_providers/Bing.yaml
    url: "https://raw.githubusercontent.com/RiverFlowsInUUU/Rule/main/magisk/Bing.yaml"
    interval: 86400
  Spotify:
    type: http
    behavior: classical
    format: yaml
    path: ./rule_providers/Spotify.yaml
    url: "https://raw.githubusercontent.com/RiverFlowsInUUU/Rule/main/magisk/Spotify.yaml"
    interval: 86400
  Openai:
    type: http
    behavior: classical
    format: yaml
    path: ./rule_providers/Openai.yaml
    url: "https://raw.githubusercontent.com/RiverFlowsInUUU/Rule/main/magisk/Openai.yaml"
    interval: 86400
  Google:
    type: http
    behavior: classical
    format: yaml
    path: ./rule_providers/Google.yaml
    url: "https://raw.githubusercontent.com/RiverFlowsInUUU/Rule/main/magisk/Google.yaml"
    interval: 86400
rules:
  - RULE-SET,Bing,â“‚ï¸ å¾®è½¯Bing
  - RULE-SET,Openai,ğŸ¤– OpenAI
  - RULE-SET,Spotify,ğŸ¶ Spotify
  - RULE-SET,Microsoft,â“‚ï¸ å¾®è½¯æœåŠ¡
  - RULE-SET,Onedrive,â“‚ï¸ å¾®è½¯äº‘ç›˜
  - RULE-SET,Google,ğŸ“¢ è°·æ­ŒæœåŠ¡
  - GEOSITE,CN,ğŸŒ ç›´è¿
  - GEOIP,private,ğŸŒ ç›´è¿,no-resolve
  - GEOIP,CN,ğŸŒ ç›´è¿,no-resolve
  - MATCH,ğŸ‹ æ¼ç½‘ä¹‹é±¼
